### PR TITLE
Get python3

### PR DESCRIPTION
**Pull request by guydemorsier**

### CODE REVIEW

**Comment by guydemorsier** [comment]
launch jenkins

**Comment by guydemorsier** [comment]
launch jenkins

**Comment by lxavier** [comment]
"launch jenkins" : @guydemorsier unfortunately there is no automatic Jenkins testing for this PR one, you have to try manually

**Comment by guydemorsier** [comment]
No PE/17.06 does not exist on arolla and you are right I need to try manually.

**Pull request closed without merging**
