### PR TITLE
Raise cuda_arch on Daint to 60

### PR DESCRIPTION
**Pull request by leuty**
Testsuite verifies [match]. Performance looks ok.

### CODE REVIEW

**Comment by lxavier** [comment]
`verifies [match]` I suppose you mean OK not MATCH, otherwise this was a cpu executable

**Comment by leuty** [comment]
Simulation with sm_60 with 120x120x60 GP/node (361x361x60 on 9 Piz Daint nodes):

 --------------------------------------------------------------------------
  Local timers:
   NCOMP_PE=    9
 --------------------------------------------------------------------------
  Id      Tag                      Ncalls         min[s]        max[s]       mean[s] 
   1      timeloop              1440      170.5032      170.5230      170.5131
  10     init                       1440        7.1319        8.0726        7.6715
  20     physics                1440       44.9021       45.8871       45.2579
  50     dynamics             1440       91.0263       93.7516       92.9165
  60     nudging               1440        0.0018        0.0020        0.0019
  80     lhn                       1440     0.0018        0.0021        0.0019
  90     diagnostics          2880        0.3648        0.3732        0.3678
 100    timefilter              1440        0.0025        0.0029        0.0027
 110    exchange_final    1440        4.1776        6.8346        4.8835
 120    output                  1440       18.0964       18.2919       18.1383
 --------------------------------------------------------------------------

The same domain with sm_35:
 --------------------------------------------------------------------------
  Local timers:
   NCOMP_PE=    9
 --------------------------------------------------------------------------
  Id      Tag           Ncalls         min[s]        max[s]       mean[s] 
   1          timeloop    1440      173.4265      173.4294      173.4274
  10              init    1440        6.4083        7.6047        6.9872
  20           physics    1440       44.9827       46.5081       45.7716
  50          dynamics    1440       93.4371       96.1761       95.4346
  60           nudging    1440        0.0017        0.0020        0.0019
  80               lhn    1440        0.0019        0.0022        0.0020
  90       diagnostics    2880        0.3636        0.3720        0.3670
 100        timefilter    1440        0.0026        0.0030        0.0028
 110    exchange_final    1440        4.0162        6.8837        4.8829
 120            output    1440       18.6147       19.1809       18.7026
 --------------------------------------------------------------------------

Testsuite with sm_60:

[------------] TESTSUITE 1.1
[------------] TEST cosmo7/test_1_gpu: Only dynamics, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py
[     OK     ] RESULT cosmo7/test_1_gpu: Only dynamics, lcpp_dycore=.TRUE.
[------------] TEST cosmo7/test_2_gpu: Dynamics and physics, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py
[     OK     ] RESULT cosmo7/test_2_gpu: Dynamics and physics, lcpp_dycore=.TRUE.
[------------] TEST cosmo7/test_3_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
[     OK     ] RESULT cosmo7/test_3_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
[------------] TEST cosmo2/test_1_gpu: Dynamics and physics, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [    OK    ] output_tolerance_check.py
[     OK     ] RESULT cosmo2/test_1_gpu: Dynamics and physics, lcpp_dycore=.TRUE.
[------------] TEST cosmo2/test_2_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [    OK    ] output_tolerance_check.py
[     OK     ] RESULT cosmo2/test_2_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
[------------] TEST cosmo2/test_sso_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [    OK    ] output_tolerance_check.py
[     OK     ] RESULT cosmo2/test_sso_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
[------------] TEST cosmo2/test_lhn_gpu: Dynamics, physics and lhn, lnudge=FALSE
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [    OK    ] output_tolerance_check.py
[     OK     ] RESULT cosmo2/test_lhn_gpu: Dynamics, physics and lhn, lnudge=FALSE
[------------] TEST cosmo2/test_sppt_gpu: SPPT, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [    OK    ] output_tolerance_check.py
[     OK     ] RESULT cosmo2/test_sppt_gpu: SPPT, lcpp_dycore=.TRUE.
[------------] TEST cosmo1/test_1_gpu: Dynamics and physics, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py
[     OK     ] RESULT cosmo1/test_1_gpu: Dynamics and physics, lcpp_dycore=.TRUE.
[------------] TEST cosmo1/test_2_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py
[     OK     ] RESULT cosmo1/test_2_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE.
[------------] TEST cosmo1/test_2_gpu_p: Decomposition test
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [  MATCH   ] identical_check.py
  [  MATCH   ] output_tolerance_check.py
[   MATCH    ] RESULT cosmo1/test_2_gpu_p: Decomposition test
[------------] TEST cosmo1/test_3_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE., hydraulic conductivity 
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py
[     OK     ] RESULT cosmo1/test_3_gpu: Dynamics, physics and assimilation, lcpp_dycore=.TRUE., hydraulic conductivity 
[------------] TEST cosmo1/test_4_gpu: COSMO-1 with old divergence damping
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [    OK    ] output_tolerance_check.py
[     OK     ] RESULT cosmo1/test_4_gpu: COSMO-1 with old divergence damping
[------------] TEST kenda/test_1_gpu: KENDA full check, lcpp_dycore=.TRUE.
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py
[     OK     ] RESULT kenda/test_1_gpu: KENDA full check, lcpp_dycore=.TRUE.
[------------] TEST flake/test_1_gpu: FLake check on GPU
  [  MATCH   ] run_success_check.py
  [  MATCH   ] existence_grib_out.sh
  [    OK    ] tolerance_check.py
  [  MATCH   ] output_tolerance_check.py

**Comment by lxavier** [comment]
perfect, thanks !

**Comment by lxavier** [comment]
I will merge it now, I love to merge things on Friday (and it is a Friday 13), and I am not here on Monday :)

**Pull request merged**
